# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RamenMen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RamenMen
	
  pod 'Firebase'

  target 'RamenMenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RamenMenUITests' do
    # Pods for testing
  end

end
